In [4]:

import numpy as numpy
import pandas as pd

In [5]:
movies = pd.read_csv('imdb-top-1000.csv')
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [6]:
genre = movies.groupby('Genre')

In [7]:
genre.sum(numeric_only=True)

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [8]:
genre.count()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,172,172,172,172,172,172,172,143
Adventure,72,72,72,72,72,72,72,72,64
Animation,82,82,82,82,82,82,82,82,75
Biography,88,88,88,88,88,88,88,88,79
Comedy,155,155,155,155,155,155,155,155,125
Crime,107,107,107,107,107,107,107,107,87
Drama,289,289,289,289,289,289,289,289,241
Family,2,2,2,2,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,11,11,11,11,11,11,11
Mystery,12,12,12,12,12,12,12,12,8
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,4,4,4,4,4

In [9]:
genre.sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [10]:

genre['Gross'].sum().sort_values(ascending=False).head(3).round(1)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [11]:
# find the genre with highest avg IMDB rating
genre['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [12]:
# find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [13]:
# find the highest rated movie of each genre
genre['IMDB_Rating'].max().sort_values(ascending=False)

Genre
Drama        9.3
Crime        9.2
Action       9.0
Biography    8.9
Western      8.8
Adventure    8.6
Comedy       8.6
Animation    8.6
Horror       8.5
Mystery      8.4
Fantasy      8.1
Film-Noir    8.1
Family       7.8
Thriller     7.8
Name: IMDB_Rating, dtype: float64

In [15]:
movies.groupby('Star1')['Star1'].value_counts().sort_values(ascending=False)

Star1
Tom Hanks               12
Robert De Niro          11
Al Pacino               10
Clint Eastwood          10
Leonardo DiCaprio        9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Ajay Devgn               1
Name: count, Length: 660, dtype: int64

In [16]:
 # find number of movies done by each actor
movies.groupby('Star1')['Star1'].value_counts().sort_values(ascending=False)

Star1
Tom Hanks               12
Robert De Niro          11
Al Pacino               10
Clint Eastwood          10
Leonardo DiCaprio        9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Ajay Devgn               1
Name: count, Length: 660, dtype: int64

In [17]:
movies['Star1'].value_counts()

Star1
Tom Hanks            12
Robert De Niro       11
Clint Eastwood       10
Al Pacino            10
Leonardo DiCaprio     9
                     ..
Phil Harris           1
David Hemmings        1
John Lennon           1
Tallulah Bankhead     1
Bruce Lee             1
Name: count, Length: 660, dtype: int64

In [18]:
# GroupBy Attributes and Methods
# find total number of groups -> len
# find items in each group -> size
# first()/last() -> nth item
# get_group -> vs filtering
# groups
# describe
# sample
# nunique

In [19]:
# find total number of groups -> len
len(movies.groupby('Genre'))

14

In [20]:
movies['Genre'].nunique()

14

In [21]:
# find items in each group -> size
movies.groupby('Genre').size().sort_values(ascending=False)

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Family         2
Fantasy        2
Thriller       1
dtype: int64

In [22]:
movies['Genre'].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [23]:
# first()/last() -> nth item
genre.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [24]:
genre.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [46]:
movies.sort_values(by='Released_Year',ascending=False)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
966,Apollo 13,PG,140,Adventure,7.6,Ron Howard,Tom Hanks,269197,173837933.0,77.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
612,The Trial of the Chicago 7,2020,129,Drama,7.8,Aaron Sorkin,Eddie Redmayne,89896,853090410.0,77.0
613,Druk,2020,117,Comedy,7.8,Thomas Vinterberg,Mads Mikkelsen,33931,349916480.0,81.0
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.0
...,...,...,...,...,...,...,...,...,...,...
193,The Gold Rush,1925,95,Adventure,8.2,Charles Chaplin,Charles Chaplin,101053,5450000.0,NaN
194,Sherlock Jr.,1924,45,Action,8.2,Buster Keaton,Buster Keaton,41985,977375.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
127,The Kid,1921,68,Comedy,8.3,Charles Chaplin,Charles Chaplin,113314,5450000.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN

In [25]:
genre.nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [26]:
# get_group -> vs filtering
genre.get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [27]:
# group
genre.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [28]:
# describe
genre.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [51]:
#  sample
genre.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
535,Dawn of the Dead,1978,127,Action,7.9,George A. Romero,David Emge,111512,5100000.0,71.0
625,Apocalypto,2006,139,Action,7.8,Mel Gibson,Gerardo Taracena,291018,50866635.0,68.0
851,Deliverance,1972,109,Adventure,7.7,John Boorman,Jon Voight,98740,7056013.0,80.0
873,The African Queen,1951,105,Adventure,7.7,John Huston,Humphrey Bogart,71481,536118.0,91.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
741,Le Petit Prince,2015,108,Animation,7.7,Mark Osborne,Jeff Bridges,56720,1339152.0,70.0
298,Inherit the Wind,1960,128,Biography,8.1,Stanley Kramer,Spencer Tracy,27254,62850934.0,75.0
622,American Gangster,2007,157,Biography,7.8,Ridley Scott,Denzel Washington,392449,130164645.0,76.0
494,In Bruges,2008,107,Comedy,7.9,Martin McDonagh,Colin Farrell,390334,7757130.0,67.0
117,The Apartment,1960,125,Comedy,8.3,Billy Wilder,Jack Lemmon,164363,18600000.0,94.0
960,Sleepers,1996,147,Crime,7.6,Barry Levinson,Robert De Niro,186734,49100000.0,49.0
198,Contratiempo,2016,106,Crime,8.1,Oriol Paulo,Mario Casas,141516,29756639.0,NaN
283,Chinatown,1974,130,Drama,8.1,Roman Polanski,Jack Nicholson,294230,29000000.0,92.0
764,Ex Machina,2014,108,Drama,7.7,Alex Garland,Alicia Vikander,474141,25442958.0,78.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
959,Dark City,1998,100,Mystery,7.6,Alex Proyas,Rufus Sewell,187927,14378331.0,66.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [29]:
genre.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [30]:
# agg method
# passing dic
genre.agg({
    'Released_Year':'max',
    'Runtime': 'mean',
    'IMDB_Rating':'max',
    'No_of_Votes':'sum',
    'Gross':'sum',
    'Metascore':'min'
    
})

,Released_Year,Runtime,IMDB_Rating,No_of_Votes,Gross,Metascore
Genre,,,,,,
Action,2019,129.046512,9.0,72282412,3.263226e+10,33.0
Adventure,PG,134.111111,8.6,22576163,9.496922e+09,41.0
Animation,2020,99.585366,8.6,21978630,1.463147e+10,61.0
Biography,2020,136.022727,8.9,24006844,8.276358e+09,48.0
Comedy,2020,112.129032,8.6,27620327,1.566387e+10,45.0
Crime,2019,126.392523,9.2,33533615,8.452632e+09,47.0
Drama,2020,124.737024,9.3,61367304,3.540997e+10,28.0
Family,1982,107.500000,7.8,551221,4.391106e+08,67.0
Fantasy,1922,85.000000,8.1,146222,7.827267e+08,NaN
Film-Noir,1949,104.000000,8.1,367215,1.259105e+08,94.0
Horror,2017,102.090909,8.5,3742556,1.034649e+09,46.0
Mystery,2012,119.083333,8.4,4203004,1.256417e+09,52.0
Thriller,1967,108.000000,7.8,27733,1.755074e+07,81.0
Western,1976,148.250000,8.8,1289665,5.822151e+07,69.0

In [31]:
num_cols = movies.select_dtypes(include='number').columns
genre[num_cols].agg(['mean','sum','median'])

              Runtime               IMDB_Rating                   No_of_Votes  \
                 mean    sum median        mean     sum median           mean
Genre
Action     129.046512  22196  127.5    7.949419  1367.3    7.9  420246.581395
Adventure  134.111111   9656  127.0    7.937500   571.5    7.9  313557.819444
Animation   99.585366   8166   99.5    7.930488   650.3    7.9  268032.073171
Biography  136.022727  11970  129.0    7.938636   698.6    7.9  272805.045455
Comedy     112.129032  17380  106.0    7.901290  1224.7    7.9  178195.658065
Crime      126.392523  13524  122.0    8.016822   857.8    8.0  313398.271028
Drama      124.737024  36049  121.0    7.957439  2299.7    8.0  212343.612457
Family     107.500000    215  107.5    7.800000    15.6    7.8  275610.500000
Fantasy     85.000000    170   85.0    8.000000    16.0    8.0   73111.000000
Film-Noir  104.000000    312  104.0    7.966667    23.9    8.0  122405.000000
Horror     102.090909   1123  103.0    7.909091    87.0    7.8  340232.363636
Mystery    119.083333   1429  117.5    7.975000    95.7    8.0  350250.333333
Thriller   108.000000    108  108.0    7.800000     7.8    7.8   27733.000000
Western    148.250000    593  148.0    8.350000    33.4    8.4  322416.250000

                                      Gross                             \
                sum    median          mean           sum       median
Genre
Action     72282412  275497.0  1.897224e+08  3.263226e+10  103858027.5
Adventure  22576163  236060.5  1.319017e+08  9.496922e+09   57160627.0
Animation  21978630  169246.0  1.784326e+08  1.463147e+10  145219819.0
Biography  24006844  188676.5  9.404952e+07  8.276358e+09   51710054.0
Comedy     27620327   88511.0  1.010572e+08  1.566387e+10   19516000.0
Crime      33533615  142107.0  7.899656e+07  8.452632e+09   16290476.0
Drama      61367304   86525.0  1.225259e+08  3.540997e+10   18500194.0
Family       551221  275610.5  2.195553e+08  4.391106e+08  219555277.0
Fantasy      146222   73111.0  3.913633e+08  7.827267e+08  391363348.0
Film-Noir    367215  148928.0  4.197018e+07  1.259105e+08    2108060.0
Horror      3742556  362393.0  9.405902e+07  1.034649e+09   56000369.0
Mystery     4203004  159514.0  1.047014e+08  1.256417e+09   31154590.0
Thriller      27733   27733.0  1.755074e+07  1.755074e+07   17550741.0
Western     1289665  267808.0  1.455538e+07  5.822151e+07   10550000.0

           Metascore
                mean      sum median
Genre
Action     73.419580  10499.0   74.0
Adventure  78.437500   5020.0   80.5
Animation  81.093333   6082.0   82.0
Biography  76.240506   6023.0   76.0
Comedy     78.720000   9840.0   79.0
Crime      77.080460   6706.0   77.0
Drama      79.701245  19208.0   82.0
Family     79.000000    158.0   79.0
Fantasy          NaN      0.0    NaN
Film-Noir  95.666667    287.0   96.0
Horror     80.000000    880.0   87.0
Mystery    79.125000    633.0   77.0
Thriller   81.000000     81.0   81.0
Western    78.250000    313.0   77.0

In [32]:
# agg method
# passing dic
genre.agg({
    'Released_Year':['max','min'],
    'Runtime': ['mean','max'],
    'IMDB_Rating':['max','min'],
    'No_of_Votes':['sum','mean'],
    'Gross':['sum','mean','min'],
    'Metascore':['min','max','mean']
    
}).round()

          Released_Year       Runtime      IMDB_Rating      No_of_Votes  \
                    max   min    mean  max         max  min         sum
Genre
Action             2019  1924   129.0  321         9.0  8.0    72282412
Adventure            PG  1925   134.0  228         9.0  8.0    22576163
Animation          2020  1940   100.0  137         9.0  8.0    21978630
Biography          2020  1928   136.0  209         9.0  8.0    24006844
Comedy             2020  1921   112.0  188         9.0  8.0    27620327
Crime              2019  1931   126.0  229         9.0  8.0    33533615
Drama              2020  1925   125.0  242         9.0  8.0    61367304
Family             1982  1971   108.0  115         8.0  8.0      551221
Fantasy            1922  1920    85.0   94         8.0  8.0      146222
Film-Noir          1949  1941   104.0  108         8.0  8.0      367215
Horror             2017  1933   102.0  122         8.0  8.0     3742556
Mystery            2012  1938   119.0  138         8.0  8.0     4203004
Thriller           1967  1967   108.0  108         8.0  8.0       27733
Western            1976  1965   148.0  165         9.0  8.0     1289665

                            Gross                           Metascore         \
               mean           sum         mean          min       min    max
Genre
Action     420247.0  3.263226e+10  189722450.0       3296.0      33.0   98.0
Adventure  313558.0  9.496922e+09  131901701.0      61001.0      41.0  100.0
Animation  268032.0  1.463147e+10  178432598.0     128985.0      61.0   96.0
Biography  272805.0  8.276358e+09   94049518.0      21877.0      48.0   97.0
Comedy     178196.0  1.566387e+10  101057214.0       1305.0      45.0   99.0
Crime      313398.0  8.452632e+09   78996560.0       6013.0      47.0  100.0
Drama      212344.0  3.540997e+10  122525862.0       3600.0      28.0  100.0
Family     275610.0  4.391106e+08  219555277.0    4000000.0      67.0   91.0
Fantasy     73111.0  7.827267e+08  391363348.0  337574718.0       NaN    NaN
Film-Noir  122405.0  1.259105e+08   41970181.0     449191.0      94.0   97.0
Horror     340232.0  1.034649e+09   94059022.0      89029.0      46.0   97.0
Mystery    350250.0  1.256417e+09  104701418.0    1035953.0      52.0  100.0
Thriller    27733.0  1.755074e+07   17550741.0   17550741.0      81.0   81.0
Western    322416.0  5.822151e+07   14555377.0    5321508.0      69.0   90.0


           mean
Genre
Action     73.0
Adventure  78.0
Animation  81.0
Biography  76.0
Comedy     79.0
Crime      77.0
Drama      80.0
Family     79.0
Fantasy     NaN
Film-Noir  96.0
Horror     80.0
Mystery    79.0
Thriller   81.0
Western    78.0

In [43]:
a = movies[movies.groupby('Genre')['IMDB_Rating'].transform('max') == movies['IMDB_Rating']]
a

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [44]:
fd = movies[movies.groupby('Genre')['IMDB_Rating']
            .transform('max') == movies['IMDB_Rating']]
fd

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [56]:
# find the highest rated movie of each genre
# looping on group

fd = pd.DataFrame(columns=movies.columns)
for group,data in genre:
    top = data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]
    fd = pd.concat([fd, top])

fd

C:\Users\HP\AppData\Local\Temp\ipykernel_16256\1861739296.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  fd = pd.concat([fd, top])

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [45]:
fd = movies.loc[movies.groupby('Genre')['IMDB_Rating'].idxmax()]
fd

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [46]:
# split (apply) combine
# apply -> builtin function
genre.apply(min)

C:\Users\HP\AppData\Local\Temp\ipykernel_16688\1770210084.py:3: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genre.apply(min)
C:\Users\HP\AppData\Local\Temp\ipykernel_16688\1770210084.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [47]:
# find number of movies starting with A for each group
def foo(group):
    
    return group['Series_Title'].str.startswith('A').sum()
genre.apply(foo)

C:\Users\HP\AppData\Local\Temp\ipykernel_16688\3739258617.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [48]:
df = pd.Series(['malik','shoaib','Ali','Ahamad'])
df.str.startswith('A').sum()

np.int64(2)

In [49]:
# find ranking of each movie in the group according to IMDB score
def rank_movies(group):
    group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
    return group

genre.apply(rank_movies)

C:\Users\HP\AppData\Local\Temp\ipykernel_16688\40601535.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(rank_movies)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              genre_rank
Genre
Action   2           1.0
         5           2.0
         8           3.5
         10          3.5
         13          6.0
...                  ...
Thriller 700         1.0
Western  12          1.0
         48          2.0
         115         3.0
         691         4.0

[1000 rows x 11 columns]

In [50]:
# find normalized IMDB rating group wise
def normal(group):
    group['Norm_Rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min()) / (group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
    return group

genre.apply(normal)

C:\Users\HP\AppData\Local\Temp\ipykernel_16688\1896845119.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              Norm_Rating
Genre
Action   2       1.000000
         5       0.928571
         8       0.857143
         10      0.857143
         13      0.785714
...                   ...
Thriller 700          NaN
Western  12      1.000000
         48      0.700000
         115     0.500000
         691     0.000000

[1000 rows x 11 columns]

In [51]:
# groupby on multiple cols
deo = movies.groupby(['Director','Star1'])

In [52]:
deo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [53]:
deo.get_group(('Aamir Khan','Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [66]:
# find the most earning actor->director combo
deo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [54]:
# find the best(in-terms of metascore(avg)) actor->genre combo
movies.groupby(['Star1','Director'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False).head()

                      Star1               Director  Metascore
418  Jean-Louis Trintignant    Bernardo Bertolucci      100.0
263          Ellar Coltrane      Richard Linklater      100.0
640            Orson Welles           Orson Welles      100.0
656           Peter O'Toole             David Lean      100.0
129          Burt Lancaster  Alexander Mackendrick      100.0

In [55]:
 # agg on multiple groupby
num_cols = movies.select_dtypes(include='number').columns
deo[num_cols].agg(['mean','sum','median'])

                                   Runtime             IMDB_Rating       \
                                      mean  sum median        mean  sum
Director            Star1
Aamir Khan          Amole Gupte      165.0  165  165.0         8.4  8.4
Aaron Sorkin        Eddie Redmayne   129.0  129  129.0         7.8  7.8
Abdellatif Kechiche Léa Seydoux      180.0  180  180.0         7.7  7.7
Abhishek Chaubey    Shahid Kapoor    148.0  148  148.0         7.8  7.8
Abhishek Kapoor     Amit Sadh        130.0  130  130.0         7.7  7.7
...                                    ...  ...    ...         ...  ...
Zaza Urushadze      Lembit Ulfsak     87.0   87   87.0         8.2  8.2
Zoya Akhtar         Hrithik Roshan   155.0  155  155.0         8.1  8.1
                    Vijay Varma      154.0  154  154.0         8.0  8.0
Çagan Irmak         Çetin Tekindor   112.0  112  112.0         8.3  8.3
Ömer Faruk Sorak    Cem Yilmaz       127.0  127  127.0         8.0  8.0

                                          No_of_Votes                    \
                                   median        mean     sum    median
Director            Star1
Aamir Khan          Amole Gupte       8.4    168895.0  168895  168895.0
Aaron Sorkin        Eddie Redmayne    7.8     89896.0   89896   89896.0
Abdellatif Kechiche Léa Seydoux       7.7    138741.0  138741  138741.0
Abhishek Chaubey    Shahid Kapoor     7.8     27175.0   27175   27175.0
Abhishek Kapoor     Amit Sadh         7.7     32628.0   32628   32628.0
...                                   ...         ...     ...       ...
Zaza Urushadze      Lembit Ulfsak     8.2     40382.0   40382   40382.0
Zoya Akhtar         Hrithik Roshan    8.1     67927.0   67927   67927.0
                    Vijay Varma       8.0     31886.0   31886   31886.0
Çagan Irmak         Çetin Tekindor    8.3     78925.0   78925   78925.0
Ömer Faruk Sorak    Cem Yilmaz        8.0     56960.0   56960   56960.0

                                          Gross                            \
                                           mean          sum       median
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0    1223869.0
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0  853090410.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0    2199675.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0  218428303.0
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0    1122527.0
...                                         ...          ...          ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0     144501.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0    3108485.0
                    Vijay Varma       5566534.0    5566534.0    5566534.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0  196206077.0

                                   Metascore
                                        mean   sum median
Director            Star1
Aamir Khan          Amole Gupte          NaN   0.0    NaN
Aaron Sorkin        Eddie Redmayne      77.0  77.0   77.0
Abdellatif Kechiche Léa Seydoux         89.0  89.0   89.0
Abhishek Chaubey    Shahid Kapoor        NaN   0.0    NaN
Abhishek Kapoor     Amit Sadh           40.0  40.0   40.0
...                                      ...   ...    ...
Zaza Urushadze      Lembit Ulfsak       73.0  73.0   73.0
Zoya Akhtar         Hrithik Roshan       NaN   0.0    NaN
                    Vijay Varma         65.0  65.0   65.0
Çagan Irmak         Çetin Tekindor       NaN   0.0    NaN
Ömer Faruk Sorak    Cem Yilmaz           NaN   0.0    NaN

[898 rows x 15 columns]

### Excercise

In [56]:
ipl = pd.read_csv('deliveries.csv')
ipl.shape

(179078, 21)

In [57]:
# find the top 10 batsman in terms of runs
ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False)

batsman
V Kohli         5434
SK Raina        5415
RG Sharma       4914
DA Warner       4741
S Dhawan        4632
                ...
RR Bhatkal         0
C Nanda            0
Abdur Razzak       0
Sunny Gupta        0
U Kaul             0
Name: batsman_runs, Length: 516, dtype: int64

In [59]:
# find the batsman with max no of sixes
six = ipl[ipl['batsman_runs'] == 6]
six.groupby('batsman')['batsman'].value_counts().sort_values(ascending=False)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
                 ...
Basil Thampi        1
WD Parnell          1
CK Langeveldt       1
A Mithun            1
A Choudhary         1
Name: count, Length: 336, dtype: int64

In [60]:
six_counts = six.groupby('batsman').size().sort_values(ascending=False)

six_counts

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
                 ...
Basil Thampi        1
WD Parnell          1
CK Langeveldt       1
A Mithun            1
A Choudhary         1
Length: 336, dtype: int64

In [61]:
six['batsman'].value_counts().head(10)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
V Kohli           191
DA Warner         181
SR Watson         177
KA Pollard        175
YK Pathan         161
Name: count, dtype: int64

In [64]:
# find batsman with most number of 4's and 6's in last 5 overs
temp_df = ipl[ipl['over'] > 15]
temp_df = temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1).index[0]

'MS Dhoni'

In [65]:
# find V Kohli's record against all teams
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [66]:
# Create a function that can return the highest score of any batsman
def check_hscore(batsman):
    temp_df = ipl[ipl['batsman'] == batsman]
    temp_df = temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1)
    return temp_df


check_hscore('CH Gayle')

match_id
411    175
Name: batsman_runs, dtype: int64